mood_suggestions = {
    "Happy": [
        "Share your happiness with someone.",
        "Make a playlist of songs you love.",
        "Dance around to your favorite music.",
        "Write a gratitude list.",
        "Take a walk and enjoy the moment.",
        "Capture your mood in a photo.",
        "Try a creative hobby like painting or writing.",
        "Send a compliment to someone.",
        "Reflect on what made you happy today.",
        "Plan something you're excited about."
    ],
    "Anxious": [
        "Practice deep breathing for 2 minutes.",
        "Do a short mindfulness meditation.",
        "Write down your worries and close the notebook.",
        "Go outside and focus on five things you see.",
        "Stretch your body gently.",
        "Drink a warm, non-caffeinated beverage.",
        "Clean up a small space around you.",
        "Color or doodle mindlessly.",
        "Count backward from 100 by threes.",
        "Say a calming mantra out loud."
    ],
    "Bored": [
        "Learn one random fact from Wikipedia.",
        "Start a short 10-minute creative project.",
        "Organize a drawer or desktop.",
        "Try a puzzle or word game online.",
        "Watch a short educational video.",
        "Write a haiku or microstory.",
        "Check out a new hobby subreddit or blog.",
        "Explore Google Earth or Street View.",
        "Browse free online courses.",
        "Draw with your non-dominant hand."
    ],
    "Sad": [
        "Write down how you feel — no filter.",
        "Watch a comfort show or video.",
        "Call or text someone you trust.",
        "Take a warm shower or bath.",
        "Go for a short walk with music.",
        "Listen to calming instrumental music.",
        "Pet an animal or watch animal videos.",
        "Look through old photos that make you smile.",
        "Wrap yourself in a cozy blanket.",
        "Make a hot drink and sip slowly."
    ],
    "Tired": [
        "Do a 5-minute body scan meditation.",
        "Drink a full glass of water.",
        "Take a screen break for 10 minutes.",
        "Stretch your back and shoulders.",
        "Lie down and close your eyes — no pressure to sleep.",
        "Listen to soft, slow music.",
        "Turn off lights and rest in silence.",
        "Do one yoga pose like child’s pose.",
        "Take five deep belly breaths.",
        "Massage your hands or temples gently."
    ],
    "Lonely": [
        "Reach out to someone you haven’t talked to in a while.",
        "Join a group chat or community online.",
        "Watch a podcast or livestream.",
        "Send a kind message to someone.",
        "Write a letter you never send.",
        "Read a story or book chapter.",
        "Spend time with a pet or stuffed animal.",
        "Write down things you like about yourself.",
        "Join an online game or activity.",
        "Listen to an uplifting talk or TEDx video."
    ],
    "Motivated": [
        "List 3 tasks you can finish today.",
        "Make progress on a project or goal.",
        "Clean a workspace and reset your vibe.",
        "Encourage someone else to do something great.",
        "Record a voice memo of an idea.",
        "Plan your next step — even if small.",
        "Track your progress in a notebook or app.",
        "Set a 15-minute timer and go all in.",
        "Review something you’ve done that made you proud.",
        "Write down your ‘why’ for staying motivated."
    ],
    "Overwhelmed": [
        "Write down your top 3 priorities.",
        "Do one 5-minute task right now.",
        "Take 5 slow, deep breaths.",
        "Step outside and feel fresh air.",
        "Say out loud: 'I am allowed to pause.'",
        "Minimize your screen or close an extra tab.",
        "Stretch and reset your posture.",
        "Draw a mind map to unload your thoughts.",
        "Ask for help — even in a small way.",
        "Do a 60-second eye or posture reset."
    ],
    "Frustrated": [
        "Punch a pillow or release energy safely.",
        "Write a rant and then delete it.",
        "Go for a brisk walk or do jumping jacks.",
        "Take a cold splash to the face.",
        "Draw a scribble and color it in.",
        "Listen to music that matches your mood.",
        "Say what’s bothering you out loud to yourself.",
        "Write a fake complaint letter for catharsis.",
        "Do something repetitive like stacking or folding.",
        "Clench and release your fists a few times."
    ],
    "Focused": [
        "Set a timer for 25 minutes of work.",
        "Turn off notifications and distractions.",
        "Write your goals clearly for the hour.",
        "Stretch your hands and wrists.",
        "Clean your workspace for clarity.",
        "Play background music or white noise.",
        "Plan a reward for after your session.",
        "Use a sticky note to mark key tasks.",
        "Stand while working for a change.",
        "Write a quick status check: What’s working?"
    ],
    "Curious": [
        "Look up a random topic you know nothing about.",
        "Read the Wikipedia 'Did You Know' section.",
        "Watch a 5-minute science or history video.",
        "Explore Google Scholar for something weird.",
        "Browse an academic journal cover page.",
        "Ask ChatGPT a strange question.",
        "Listen to a curiosity-driven podcast.",
        "Try a new recipe, no matter how small.",
        "Read a fun fact book or calendar.",
        "Look at constellations or space photos."
    ],
    "Grateful": [
        "Write down 3 things you’re thankful for.",
        "Send a thank-you text to someone.",
        "Reflect on one challenge you overcame.",
        "Make a collage or journal entry about joy.",
        "Smile at yourself in the mirror.",
        "Appreciate something small around you right now.",
        "Think about a teacher or mentor who helped you.",
        "Say thank you aloud — even to yourself.",
        "Revisit photos of good memories.",
        "Make a list of things money can't buy."
    ],
    "Disconnected": [
        "Unplug from social media for 15 minutes.",
        "Stand outside and feel the weather on your skin.",
        "Walk barefoot or touch something natural.",
        "Listen to ambient nature sounds.",
        "Write something by hand instead of typing.",
        "Stretch without a screen for 5 minutes.",
        "Name 3 things you can smell, hear, and feel.",
        "Make or eat something without distractions.",
        "Do a quick digital declutter (emails, files, tabs).",
        "Take 3 full breaths while doing absolutely nothing."
    ]
}
mood_emojis = {
    "Happy": "😁",
    "Anxious": "😰",
    "Bored": "😐",
    "Sad": "😢",
    "Tired": "😴",
    "Lonely": "😔",
    "Motivated": "💪",
    "Overwhelmed": "😵",
    "Frustrated": "😡",
    "Focused": "🎯",
    "Curious": "🧐",
    "Grateful": "😇",
    "Disconnected": "🤯"
}